# Primary accent for interactive elements
primaryColor = '#ADD8E6'

# Background color for the main content area
backgroundColor = '#273346'

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = '#ADD8E6'

# Color used for almost all text
textColor = '#ADD8E6'

# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace) 
# Default: "sans serif"
font = "sans serif"